name: "Arch Linux User Repository (AUR) GitHub Action"
description: ""
author: "JamieMagee"
branding:
  icon: "package"
  color: "blue"

inputs:
  action:
    description: "Which action to take. Can be 'updpkgsums' or 'publish'"
    required: true
  pkgname:
    description: ""
    required: true

runs:
  using: docker
  image: "Dockerfile"
  args:
    - ${{ inputs.action }}
    - ${{ inputs.pkgname }}
